name: Build and deploy to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1

      - name: Install, lint, build 🔧
      env: 
          REACT_APP_GOOGLE_CLIEN_ID: ${{ secrets.REACT_APP_GOOGLE_CLIEN_ID }}
        run: |
          npm install
          npm run lint:js
          npm run build

      - name: Deploy 🚀
      env: 
          REACT_APP_GOOGLE_CLIEN_ID: ${{ secrets.REACT_APP_GOOGLE_CLIEN_ID }}
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages
          folder: build
